services:
    _defaults:
        autowire: true
        autoconfigure: true

    Lentille\SymfonyBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Attribute/'
            - '../src/LentilleSymfonyBundle.php'
