<?php declare(strict_types=1);

namespace Lentille\SymfonyBundle\Frontend;

use Lentille\SymfonyBundle\Frontend\ConfigEntry\ConfigEntryInterface;
use Lentille\SymfonyBundle\Frontend\ConfigEntry\ConfigGetterArgs;
use Symfony\Component\Config\ConfigCacheFactory;
use Symfony\Component\Config\ConfigCacheFactoryInterface;
use Symfony\Component\Config\ConfigCacheInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\DependencyInjection\Attribute\TaggedIterator;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerInterface;

class FrontendConfig implements CacheWarmerInterface {
	private readonly ConfigCacheFactoryInterface $configCacheFactory;
	private static ?array $cache = [];

	public function __construct(
		#[Autowire('%kernel.debug%')] bool $isDebug,
		#[Autowire('%kernel.cache_dir%')] private string $cacheDir,
		#[TaggedIterator('lentille.frontend_config.entry')] private readonly iterable $entries,
		#[Autowire('%kernel.default_locale%')] private readonly string $defaultLocale,
		#[Autowire('%kernel.enabled_locales%')] private readonly array $enabledLocales,
		private readonly array $warmupLocales = [],
		private readonly array $instances = ['main']
	) {
		$this->configCacheFactory = new ConfigCacheFactory($isDebug);
	}

	public function getConfig(string $instance, ?string $locale = null): array {
		if(!in_array($instance, $this->instances)) {
			throw new \InvalidArgumentException('Unknown instance');
		}
		$args = new ConfigGetterArgs(
			instance: $instance,
			locale: $locale ?: $this->defaultLocale
		);
		$cache = $this->configCacheFactory->cache(
			$this->cacheDir."/frontend_config+{$args->instance}+{$args->locale}.php",
			fn(ConfigCacheInterface $cache) => $cache->write($this->dumpConfig($args))
		);
		return $this->getCompiledConfig($cache->getPath());
	}

	public function warmUp(string $cacheDir): array {
		$oldCache = $this->cacheDir;
		$this->cacheDir = $cacheDir;

		foreach($this->instances as $i) {
			foreach(array_unique(array_merge(
				$this->enabledLocales,
				$this->warmupLocales,
				[$this->defaultLocale]
			)) as $l) {
				$this->getConfig($i, $l);
			}
		}

		$this->cacheDir = $oldCache;
		return [];
	}

	public function isOptional(): bool {
		return false;
	}

	private function dumpConfig(ConfigGetterArgs $args): string {
		$vars = [];
		/** @var ConfigEntryInterface $entry */
		foreach($this->entries as $entry) {
			$vars += $entry->getConfig($args);
		}
		$vars['_locale'] = $args->locale;
		$vars['_instance'] = $args->instance;
		$vars['_version'] = $hash = hash('xxh64', json_encode($vars, JSON_UNESCAPED_UNICODE));
		$json = json_encode($vars, JsonResponse::DEFAULT_ENCODING_OPTIONS);
		$return = var_export([$hash, $vars, $json], true);
		return <<<EOF
<?php // This file has been auto-generated by the Lentille Symfony Bundle.
// Frontend instance: {$args->instance}, locale: {$args->locale}
return $return;
EOF;
	}

	private function getCompiledConfig(string $path): array {
		if(
			[] === self::$cache &&
			\function_exists('opcache_invalidate') &&
			filter_var(ini_get('opcache.enable'), \FILTER_VALIDATE_BOOLEAN) &&
			(!\in_array(\PHP_SAPI, ['cli', 'phpdbg'], true) || filter_var(ini_get('opcache.enable_cli'), \FILTER_VALIDATE_BOOLEAN))
		) {
			self::$cache = null;
		}

		if(null === self::$cache) {
			return require $path;
		}

		return self::$cache[$path] ??= require $path;
	}
}
